// flow-typed signature: 508ffa4e0d6815a765dcf8300a00f809
// flow-typed version: <<STUB>>/eslint-plugin-simple-import-sort_v^4.0.0/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-simple-import-sort'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-simple-import-sort' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-simple-import-sort/src' {
  declare module.exports: any;
}

declare module 'eslint-plugin-simple-import-sort/src/sort' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-simple-import-sort/src/index' {
  declare module.exports: $Exports<'eslint-plugin-simple-import-sort/src'>;
}
declare module 'eslint-plugin-simple-import-sort/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-simple-import-sort/src'>;
}
declare module 'eslint-plugin-simple-import-sort/src/sort.js' {
  declare module.exports: $Exports<'eslint-plugin-simple-import-sort/src/sort'>;
}
