// flow-typed signature: 720015f2babb4a18793a294d7e491433
// flow-typed version: <<STUB>>/styled-reset_v2.0.17/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-reset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-reset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-reset/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-reset/lib/index' {
  declare module.exports: $Exports<'styled-reset/lib'>;
}
declare module 'styled-reset/lib/index.js' {
  declare module.exports: $Exports<'styled-reset/lib'>;
}
